language: python

python:
  - '2.6'
  - '2.7'

env:
  - TOXENV=py26,py27

# command to install dependencies
install:
  - pip install tox multiprocessing coveralls

# command to run tests
script:
  - tox

after_success:
  - coveralls